#Expyriment 1.0.0 (Python 3.11.9), .xpe-file, coding: cp1252
#date: Sat Oct 11 2025 21:20:36
#sha1: fe4b42
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='zlr778', release='10', version='10.0.22631', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
1628,design,log,
#design: #exp: Blindspot
#design: block_cnt,block_id,trial_cnt,trial_id
1628,design,logged,
1628,Experiment,started
1642,Stimulus,presented,0
1642,stderr,received,'Traceback (most recent call last):'
1642,stderr,received,'  File "C:\\Users\\20946\\CogSup\\Programming\\Assignments\\Week-5\\Exercises\\blindspot.py", line 58, in <module>'
1643,stderr,received,'    run_trial()'
1644,stderr,received,'  File "C:\\Users\\20946\\CogSup\\Programming\\Assignments\\Week-5\\Exercises\\blindspot.py", line 35, in run_trial'
1644,stderr,received,'    circle.present(clear = False, update = True)'
1644,stderr,received,'    ^^^^^^'
1645,stderr,received,"UnboundLocalError: cannot access local variable 'circle' where it is not associated with a value"
